services:
  web:
    image: nginx:1.26.1-alpine
    container_name: react_app
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    # # Mount custom Nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped